package com.trs.model;

public class KnowledgeSegmentBookWithBLOBs extends KnowledgeSegmentBook {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column knowledge_segment_book.textcontent
     *
     * @mbggenerated
     */
    private String textcontent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column knowledge_segment_book.htmlcontent
     *
     * @mbggenerated
     */
    private String htmlcontent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column knowledge_segment_book.textcontent
     *
     * @return the value of knowledge_segment_book.textcontent
     *
     * @mbggenerated
     */
    public String getTextcontent() {
        return textcontent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column knowledge_segment_book.textcontent
     *
     * @param textcontent the value for knowledge_segment_book.textcontent
     *
     * @mbggenerated
     */
    public void setTextcontent(String textcontent) {
        this.textcontent = textcontent == null ? null : textcontent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column knowledge_segment_book.htmlcontent
     *
     * @return the value of knowledge_segment_book.htmlcontent
     *
     * @mbggenerated
     */
    public String getHtmlcontent() {
        return htmlcontent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column knowledge_segment_book.htmlcontent
     *
     * @param htmlcontent the value for knowledge_segment_book.htmlcontent
     *
     * @mbggenerated
     */
    public void setHtmlcontent(String htmlcontent) {
        this.htmlcontent = htmlcontent == null ? null : htmlcontent.trim();
    }
}