package com.trs.model;

public class KnowledgeSegmentBook {

    public int size;

    public int page;

    public void setSize(int size) {
        this.size = size;
    }

    public void setPage(int page) {
        this.page = page;
    }

    public int getSize() {

        return size;
    }

    public int getPage() {
        return page;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column knowledge_segment_book.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column knowledge_segment_book.knowledgeid
     *
     * @mbggenerated
     */
    private String knowledgeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column knowledge_segment_book.propertyname
     *
     * @mbggenerated
     */
    private String propertyname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column knowledge_segment_book.bookname
     *
     * @mbggenerated
     */
    private String bookname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column knowledge_segment_book.isbn
     *
     * @mbggenerated
     */
    private String isbn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column knowledge_segment_book.chapterpath
     *
     * @mbggenerated
     */
    private String chapterpath;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column knowledge_segment_book.id
     *
     * @return the value of knowledge_segment_book.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column knowledge_segment_book.id
     *
     * @param id the value for knowledge_segment_book.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column knowledge_segment_book.knowledgeid
     *
     * @return the value of knowledge_segment_book.knowledgeid
     *
     * @mbggenerated
     */
    public String getKnowledgeid() {
        return knowledgeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column knowledge_segment_book.knowledgeid
     *
     * @param knowledgeid the value for knowledge_segment_book.knowledgeid
     *
     * @mbggenerated
     */
    public void setKnowledgeid(String knowledgeid) {
        this.knowledgeid = knowledgeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column knowledge_segment_book.propertyname
     *
     * @return the value of knowledge_segment_book.propertyname
     *
     * @mbggenerated
     */
    public String getPropertyname() {
        return propertyname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column knowledge_segment_book.propertyname
     *
     * @param propertyname the value for knowledge_segment_book.propertyname
     *
     * @mbggenerated
     */
    public void setPropertyname(String propertyname) {
        this.propertyname = propertyname == null ? null : propertyname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column knowledge_segment_book.bookname
     *
     * @return the value of knowledge_segment_book.bookname
     *
     * @mbggenerated
     */
    public String getBookname() {
        return bookname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column knowledge_segment_book.bookname
     *
     * @param bookname the value for knowledge_segment_book.bookname
     *
     * @mbggenerated
     */
    public void setBookname(String bookname) {
        this.bookname = bookname == null ? null : bookname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column knowledge_segment_book.isbn
     *
     * @return the value of knowledge_segment_book.isbn
     *
     * @mbggenerated
     */
    public String getIsbn() {
        return isbn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column knowledge_segment_book.isbn
     *
     * @param isbn the value for knowledge_segment_book.isbn
     *
     * @mbggenerated
     */
    public void setIsbn(String isbn) {
        this.isbn = isbn == null ? null : isbn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column knowledge_segment_book.chapterpath
     *
     * @return the value of knowledge_segment_book.chapterpath
     *
     * @mbggenerated
     */
    public String getChapterpath() {
        return chapterpath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column knowledge_segment_book.chapterpath
     *
     * @param chapterpath the value for knowledge_segment_book.chapterpath
     *
     * @mbggenerated
     */
    public void setChapterpath(String chapterpath) {
        this.chapterpath = chapterpath == null ? null : chapterpath.trim();
    }
}