package com.trs.model;

import java.text.SimpleDateFormat;
import java.util.Date;

public class KnowledgeReview {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column knowledge_review.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column knowledge_review.create_user
     *
     * @mbggenerated
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column knowledge_review.manager
     *
     * @mbggenerated
     */
    private String manager;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column knowledge_review.knowledge_name
     *
     * @mbggenerated
     */
    private String knowledgeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column knowledge_review.create_date
     *
     * @mbggenerated
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column knowledge_review.examine_date
     *
     * @mbggenerated
     */
    private Date examineDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column knowledge_review.status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column knowledge_review.ip
     *
     * @mbggenerated
     */
    private String ip;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column knowledge_review.id
     *
     * @return the value of knowledge_review.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column knowledge_review.id
     *
     * @param id the value for knowledge_review.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column knowledge_review.create_user
     *
     * @return the value of knowledge_review.create_user
     *
     * @mbggenerated
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column knowledge_review.create_user
     *
     * @param createUser the value for knowledge_review.create_user
     *
     * @mbggenerated
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column knowledge_review.manager
     *
     * @return the value of knowledge_review.manager
     *
     * @mbggenerated
     */
    public String getManager() {
        return manager;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column knowledge_review.manager
     *
     * @param manager the value for knowledge_review.manager
     *
     * @mbggenerated
     */
    public void setManager(String manager) {
        this.manager = manager == null ? null : manager.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column knowledge_review.knowledge_name
     *
     * @return the value of knowledge_review.knowledge_name
     *
     * @mbggenerated
     */
    public String getKnowledgeName() {
        return knowledgeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column knowledge_review.knowledge_name
     *
     * @param knowledgeName the value for knowledge_review.knowledge_name
     *
     * @mbggenerated
     */
    public void setKnowledgeName(String knowledgeName) {
        this.knowledgeName = knowledgeName == null ? null : knowledgeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column knowledge_review.create_date
     *
     * @return the value of knowledge_review.create_date
     *
     * @mbggenerated
     */
    public String getCreateDate() {
        SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
        return formatter.format(createDate);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column knowledge_review.create_date
     *
     * @param createDate the value for knowledge_review.create_date
     *
     * @mbggenerated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column knowledge_review.examine_date
     *
     * @return the value of knowledge_review.examine_date
     *
     * @mbggenerated
     */
    public String getExamineDate() {
        try {
        SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
        return formatter.format(examineDate);
        }catch (Exception e){
            return null;
        }
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column knowledge_review.examine_date
     *
     * @param examineDate the value for knowledge_review.examine_date
     *
     * @mbggenerated
     */
    public void setExamineDate(Date examineDate) {
        this.examineDate = examineDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column knowledge_review.status
     *
     * @return the value of knowledge_review.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column knowledge_review.status
     *
     * @param status the value for knowledge_review.status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column knowledge_review.ip
     *
     * @return the value of knowledge_review.ip
     *
     * @mbggenerated
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column knowledge_review.ip
     *
     * @param ip the value for knowledge_review.ip
     *
     * @mbggenerated
     */
    public void setIp(String ip) {
        this.ip = ip == null ? null : ip.trim();
    }
}