package com.trs.model;

import java.text.SimpleDateFormat;
import java.util.Date;

public class SearchHistory {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column search_history.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column search_history.searchname
     *
     * @mbggenerated
     */
    private String searchname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column search_history.searchurl
     *
     * @mbggenerated
     */
    private String searchurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column search_history.userid
     *
     * @mbggenerated
     */
    private String userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column search_history.createtime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column search_history.status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column search_history.ip
     *
     * @mbggenerated
     */
    private String ip;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column search_history.id
     *
     * @return the value of search_history.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column search_history.id
     *
     * @param id the value for search_history.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column search_history.searchname
     *
     * @return the value of search_history.searchname
     *
     * @mbggenerated
     */
    public String getSearchname() {
        return searchname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column search_history.searchname
     *
     * @param searchname the value for search_history.searchname
     *
     * @mbggenerated
     */
    public void setSearchname(String searchname) {
        this.searchname = searchname == null ? null : searchname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column search_history.searchurl
     *
     * @return the value of search_history.searchurl
     *
     * @mbggenerated
     */
    public String getSearchurl() {
        return searchurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column search_history.searchurl
     *
     * @param searchurl the value for search_history.searchurl
     *
     * @mbggenerated
     */
    public void setSearchurl(String searchurl) {
        this.searchurl = searchurl == null ? null : searchurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column search_history.userid
     *
     * @return the value of search_history.userid
     *
     * @mbggenerated
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column search_history.userid
     *
     * @param userid the value for search_history.userid
     *
     * @mbggenerated
     */
    public void setUserid(String userid) {
        this.userid = userid == null ? null : userid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column search_history.createtime
     *
     * @return the value of search_history.createtime
     *
     * @mbggenerated
     */
    public String getCreatetime() {
        SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
        return formatter.format(createtime);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column search_history.createtime
     *
     * @param createtime the value for search_history.createtime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column search_history.status
     *
     * @return the value of search_history.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column search_history.status
     *
     * @param status the value for search_history.status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column search_history.ip
     *
     * @return the value of search_history.ip
     *
     * @mbggenerated
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column search_history.ip
     *
     * @param ip the value for search_history.ip
     *
     * @mbggenerated
     */
    public void setIp(String ip) {
        this.ip = ip == null ? null : ip.trim();
    }
}