package com.trs.model;

public class ThesaurusWithBLOBs extends Thesaurus {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column thesaurus.parent
     *
     * @mbggenerated
     */
    private String parent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column thesaurus.creator
     *
     * @mbggenerated
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column thesaurus.editor
     *
     * @mbggenerated
     */
    private String editor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column thesaurus.thesaurus
     *
     * @mbggenerated
     */
    private String thesaurus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column thesaurus.aboutword
     *
     * @mbggenerated
     */
    private String aboutword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column thesaurus.aboutphrase
     *
     * @mbggenerated
     */
    private byte[] aboutphrase;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column thesaurus.similarphrase
     *
     * @mbggenerated
     */
    private byte[] similarphrase;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column thesaurus.parent
     *
     * @return the value of thesaurus.parent
     *
     * @mbggenerated
     */
    public String getParent() {
        return parent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column thesaurus.parent
     *
     * @param parent the value for thesaurus.parent
     *
     * @mbggenerated
     */
    public void setParent(String parent) {
        this.parent = parent == null ? null : parent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column thesaurus.creator
     *
     * @return the value of thesaurus.creator
     *
     * @mbggenerated
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column thesaurus.creator
     *
     * @param creator the value for thesaurus.creator
     *
     * @mbggenerated
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column thesaurus.editor
     *
     * @return the value of thesaurus.editor
     *
     * @mbggenerated
     */
    public String getEditor() {
        return editor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column thesaurus.editor
     *
     * @param editor the value for thesaurus.editor
     *
     * @mbggenerated
     */
    public void setEditor(String editor) {
        this.editor = editor == null ? null : editor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column thesaurus.thesaurus
     *
     * @return the value of thesaurus.thesaurus
     *
     * @mbggenerated
     */
    public String getThesaurus() {
        return thesaurus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column thesaurus.thesaurus
     *
     * @param thesaurus the value for thesaurus.thesaurus
     *
     * @mbggenerated
     */
    public void setThesaurus(String thesaurus) {
        this.thesaurus = thesaurus == null ? null : thesaurus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column thesaurus.aboutword
     *
     * @return the value of thesaurus.aboutword
     *
     * @mbggenerated
     */
    public String getAboutword() {
        return aboutword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column thesaurus.aboutword
     *
     * @param aboutword the value for thesaurus.aboutword
     *
     * @mbggenerated
     */
    public void setAboutword(String aboutword) {
        this.aboutword = aboutword == null ? null : aboutword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column thesaurus.aboutphrase
     *
     * @return the value of thesaurus.aboutphrase
     *
     * @mbggenerated
     */
    public String getAboutphrase() {
        try {
        return new String(aboutphrase,"UTF-8");
        }catch (Exception e){
            return "";
        }
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column thesaurus.aboutphrase
     *
     * @param aboutphrase the value for thesaurus.aboutphrase
     *
     * @mbggenerated
     */
    public void setAboutphrase(byte[] aboutphrase) {
        this.aboutphrase = aboutphrase;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column thesaurus.similarphrase
     *
     * @return the value of thesaurus.similarphrase
     *
     * @mbggenerated
     */
    public String getSimilarphrase() {
        try {
        return new String(similarphrase,"UTF-8");
        }catch (Exception e){
            return "";
        }
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column thesaurus.similarphrase
     *
     * @param similarphrase the value for thesaurus.similarphrase
     *
     * @mbggenerated
     */
    public void setSimilarphrase(byte[] similarphrase) {
        this.similarphrase = similarphrase;
    }
}