package com.trs.model;

import java.text.SimpleDateFormat;
import java.util.Date;

public class Thesaurus {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column thesaurus.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column thesaurus.word
     *
     * @mbggenerated
     */
    private String word;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column thesaurus.molecular_formula
     *
     * @mbggenerated
     */
    private String molecularFormula;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column thesaurus.abbreviation
     *
     * @mbggenerated
     */
    private String abbreviation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column thesaurus.foreignword
     *
     * @mbggenerated
     */
    private String foreignword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column thesaurus.create_date
     *
     * @mbggenerated
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column thesaurus.update_date
     *
     * @mbggenerated
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column thesaurus.status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column thesaurus.id
     *
     * @return the value of thesaurus.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column thesaurus.id
     *
     * @param id the value for thesaurus.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column thesaurus.word
     *
     * @return the value of thesaurus.word
     *
     * @mbggenerated
     */
    public String getWord() {
        return word;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column thesaurus.word
     *
     * @param word the value for thesaurus.word
     *
     * @mbggenerated
     */
    public void setWord(String word) {
        this.word = word == null ? null : word.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column thesaurus.molecular_formula
     *
     * @return the value of thesaurus.molecular_formula
     *
     * @mbggenerated
     */
    public String getMolecularFormula() {
        return molecularFormula;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column thesaurus.molecular_formula
     *
     * @param molecularFormula the value for thesaurus.molecular_formula
     *
     * @mbggenerated
     */
    public void setMolecularFormula(String molecularFormula) {
        this.molecularFormula = molecularFormula == null ? null : molecularFormula.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column thesaurus.abbreviation
     *
     * @return the value of thesaurus.abbreviation
     *
     * @mbggenerated
     */
    public String getAbbreviation() {
        return abbreviation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column thesaurus.abbreviation
     *
     * @param abbreviation the value for thesaurus.abbreviation
     *
     * @mbggenerated
     */
    public void setAbbreviation(String abbreviation) {
        this.abbreviation = abbreviation == null ? null : abbreviation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column thesaurus.foreignword
     *
     * @return the value of thesaurus.foreignword
     *
     * @mbggenerated
     */
    public String getForeignword() {
        return foreignword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column thesaurus.foreignword
     *
     * @param foreignword the value for thesaurus.foreignword
     *
     * @mbggenerated
     */
    public void setForeignword(String foreignword) {
        this.foreignword = foreignword == null ? null : foreignword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column thesaurus.create_date
     *
     * @return the value of thesaurus.create_date
     *
     * @mbggenerated
     */
    public String getCreateDate() {
        SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
        return formatter.format(createDate);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column thesaurus.create_date
     *
     * @param createDate the value for thesaurus.create_date
     *
     * @mbggenerated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column thesaurus.update_date
     *
     * @return the value of thesaurus.update_date
     *
     * @mbggenerated
     */
    public String getUpdateDate() {
        SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
        return formatter.format(updateDate);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column thesaurus.update_date
     *
     * @param updateDate the value for thesaurus.update_date
     *
     * @mbggenerated
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column thesaurus.status
     *
     * @return the value of thesaurus.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column thesaurus.status
     *
     * @param status the value for thesaurus.status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}