package com.trs.model;

public class ThesaurusCoreWord {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column thesaurus_core_word.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column thesaurus_core_word.word
     *      主题词
     * @mbggenerated
     */
    private String word;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column thesaurus_core_word.attribute
     *      属性
     * @mbggenerated
     */
    private String attribute;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column thesaurus_core_word.core_word
     *      核心词
     * @mbggenerated
     */
    private String coreWord;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column thesaurus_core_word.id
     *
     * @return the value of thesaurus_core_word.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column thesaurus_core_word.id
     *
     * @param id the value for thesaurus_core_word.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column thesaurus_core_word.word
     *
     * @return the value of thesaurus_core_word.word
     *
     * @mbggenerated
     */
    public String getWord() {
        return word;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column thesaurus_core_word.word
     *
     * @param word the value for thesaurus_core_word.word
     *
     * @mbggenerated
     */
    public void setWord(String word) {
        this.word = word == null ? null : word.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column thesaurus_core_word.attribute
     *
     * @return the value of thesaurus_core_word.attribute
     *
     * @mbggenerated
     */
    public String getAttribute() {
        return attribute;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column thesaurus_core_word.attribute
     *
     * @param attribute the value for thesaurus_core_word.attribute
     *
     * @mbggenerated
     */
    public void setAttribute(String attribute) {
        this.attribute = attribute == null ? null : attribute.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column thesaurus_core_word.core_word
     *
     * @return the value of thesaurus_core_word.core_word
     *
     * @mbggenerated
     */
    public String getCoreWord() {
        return coreWord;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column thesaurus_core_word.core_word
     *
     * @param coreWord the value for thesaurus_core_word.core_word
     *
     * @mbggenerated
     */
    public void setCoreWord(String coreWord) {
        this.coreWord = coreWord == null ? null : coreWord.trim();
    }
}