package com.trs.mapper;

import com.trs.model.KnowledgeReview;
import com.trs.model.KnowledgeReviewWithBLOBs;

import java.util.List;
import java.util.Map;

public interface KnowledgeReviewMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table knowledge_review
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table knowledge_review
     *
     * @mbggenerated
     */
    int insert(KnowledgeReviewWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table knowledge_review
     *
     * @mbggenerated
     */
    int insertSelective(KnowledgeReviewWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table knowledge_review
     *
     * @mbggenerated
     */
    KnowledgeReviewWithBLOBs selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table knowledge_review
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(KnowledgeReviewWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table knowledge_review
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(KnowledgeReviewWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table knowledge_review
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(KnowledgeReview record);

    List<KnowledgeReview> findAll(Map map);

    int total(Map map);
}