package com.trs.mapper;

import com.trs.model.KnowledgeSegmentBook;
import com.trs.model.KnowledgeSegmentBookWithBLOBs;

import java.util.List;
import java.util.Map;
import java.util.Set;

public interface KnowledgeSegmentBookMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table knowledge_segment_book
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);
    int deleteAll();

    int deleteByKnowledgeId(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table knowledge_segment_book
     *
     * @mbggenerated
     */
    int insert(KnowledgeSegmentBookWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table knowledge_segment_book
     *
     * @mbggenerated
     */
    int insertSelective(KnowledgeSegmentBookWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table knowledge_segment_book
     *
     * @mbggenerated
     */
    KnowledgeSegmentBookWithBLOBs selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table knowledge_segment_book
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(KnowledgeSegmentBookWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table knowledge_segment_book
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(KnowledgeSegmentBookWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table knowledge_segment_book
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(KnowledgeSegmentBook record);

    //通过id name 章节号 查询书，实体类id不能为空，其余可为空。
    List findByINCProerty(KnowledgeSegmentBook record);
    List findBlobsByINCProerty(KnowledgeSegmentBook record);

    /**
     * 统计每个属性关联的图书数
     * @param
     * @return
     */
    int countPropertyBook(Map map);

    /**
     * 查询知识元属性
     * @param knowledgeName
     * @return
     */
    List<String> selectPropertyByKnowledgeName(String knowledgeName);
    public Set<String> selectAllWords();

    /**
     * 查询书名
     */
    public List<String> findBookName(Map map);
}