package com.trs.mapper;

import com.trs.model.Member;
import org.springframework.stereotype.Component;

import java.util.List;
import java.util.Map;

@Component
public interface MemberMapperOnline {
    int insert(Member record);

    /***
     * 修改密码和用户信息
     * @param record
     * @return
     */
    int updateByPrimaryKeySelective(Member record);
    /**
     * 查询会员
     * @param userName
     * @return
     */
    public Member findMemberByUserName(String userName);
    /**
     * 查询所有会员
     * @param map
     * @return
     */
    public List<Member> listAllMember(Map map);

    public  List<Member> listAllOrganizeMember(Map map);

    /**
     * 查询数据总数
     * @param map
     * @return
     */
    int total(Map map);

    int OrganizeTotal(Map map);

    Member selectByPrimaryKey(Integer id);

    /**
     * 更改状态
     * @param map
     */
    void changeStatus(Map map);

    int deleteByPrimaryKey(Integer id);

    /**
     * 查找角色是否被占用
     * @param member
     * @return
     */
    List<Member> findMemberByRoleId(Member member);

    /**
     * 更改权限
     * @param map
     */
    void changRoleId(Map map);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Member record);

    /**
     * 修改用户信息
     * @param map
     * @return
     */
    int updataOrganize(Map map);

    /**
     * 修改用户信息
     * @param map
     * @return
     */
    int updataOrganizeByUserName(Map map);


    /**
     * 查询根据机构ID
     * @param map
     * @return
     */
    public List<Member> findMemberByOrgId(Map map);
}
