package com.trs.mapper;

import com.trs.model.Member;

import java.util.List;
import java.util.Map;

public interface MemberMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member
     *
     * @mbggenerated
     */
    int insert(Member record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member
     *
     * @mbggenerated
     */
    int insertSelective(Member record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member
     *
     * @mbggenerated
     */
    Member selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Member record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Member record);

    /**
     * 查询所有会员
     * @param map
     * @return
     */
    public List<Member> listAllMember(Map map);

    /**
     * 查询数据总数
     * @param map
     * @return
     */
    int total(Map map);

    /**
     * 更改资源状态
     * @param map
     */
    void changeStatus(Map map);

    /**
     * 更改权限
     * @param map
     */
    void changRoleId(Map map);

    /**
     * 查找角色是否被占用
     * @param member
     * @return
     */
    List<Member> findMemberByRoleId(Member member);

    /**
     * 查询会员
     * @param userName
     * @return
     */
    public Member findMemberByUserName(String userName);

    /**
     * 查询会员
     * @param email
     * @return
     */
    public List<Member> findMemberByEmail(String email);

    /**
     * 添加会员
     * @param member
     */
    public void add(Member member);

    /**
     * 修改用户信息
     * @param map
     * @return
     */
    int updataOrganize(Map map);


    /**
     * 修改用户信息
     * @param map
     * @return
     */
    int updataOrganizeByUserName(Map map);


    /**
     * 查询根据机构ID
     * @param map
     * @return
     */
    public List<Member> findMemberByOrgId(Map map);

}