package com.trs.mapper;

import com.trs.model.Role;
import com.trs.model.RolePermission;
import org.springframework.stereotype.Component;

import java.util.List;
import java.util.Map;

@Component
public interface RoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role
     *
     * @mbggenerated
     */
    int insert(Role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role
     *
     * @mbggenerated
     */
    int insertSelective(Role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role
     *
     * @mbggenerated
     */
    Role selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Role record);

    /**
     * 查询所有角色
     * @return
     */
    List<Role> findAll(Map<String, Object> map);

    /***
     * 返回数据总数
     * @param map
     * @return
     */
    public int total(Map<String, Object> map);

    /**
     * 查询所有角色
     * @return
     */
    List<Role> findAllRole(int attribute);

    /**
     * 通过名称查询角色
     * @param name
     * @return
     */
    public Role findRoleByName(String name);

}