package com.trs.mapper;

import com.trs.model.SearchHistory;
import org.apache.ibatis.annotations.Param;

import java.util.List;
import java.util.Map;

public interface SearchHistoryMapper {

    /**
     * 分页查询搜索历史
     * @return
     */
    public List<SearchHistory> findAll(Map map);
    /**
     * 获取搜索历史总记录数
     *
     * @return
     */
    public int total(Map map);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table search_history
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table search_history
     *
     * @mbggenerated
     */
    int insert(SearchHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table search_history
     *
     * @mbggenerated
     */
    int insertSelective(SearchHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table search_history
     *
     * @mbggenerated
     */
    SearchHistory selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table search_history
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SearchHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table search_history
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SearchHistory record);

    int updateStatusByUserid(SearchHistory record);

    public int pageList(Map map);

    List getHotSearchWord(Map map);

    List<Map<String,Object>> resultDataExcelBookDetails(@Param("type") String type, @Param("bookCode") String[] bookCode, @Param("zid") String[] zid);

    List<Map<String,Object>> resultDataExcelBook(@Param("bookCode") String[] bookCode);
}