package com.trs.mapper;

import com.trs.model.Thesaurus;
import com.trs.model.ThesaurusWithBLOBs;

import java.util.List;
import java.util.Map;

public interface ThesaurusMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thesaurus
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thesaurus
     *
     * @mbggenerated
     */
    int insert(ThesaurusWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thesaurus
     *
     * @mbggenerated
     */
    int insertSelective(ThesaurusWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thesaurus
     *
     * @mbggenerated
     */
    ThesaurusWithBLOBs selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thesaurus
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ThesaurusWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thesaurus
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(ThesaurusWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thesaurus
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Thesaurus record);

    ThesaurusWithBLOBs selectByWord(String word);

     List<ThesaurusWithBLOBs> findAll(Map map);

     int total(Map map);

    List<ThesaurusWithBLOBs> selectByParentWithBLOBS(String word);
    List<String> selectByParent(String word);
    int countChildNumber(String word);
    List<String> findAllWord();
}